Menu.create(navigation_name: "Roles", controller_name: "roles", icon: "fa-user-cog")
Menu.create(navigation_name: "Empleados", controller_name: "employees", icon: 'fa-users')
Menu.create(navigation_name: "Laboratorios", controller_name: "laboratories", icon: 'fa-city')
Menu.create(navigation_name: "Clientes", controller_name: "clients", icon: 'fa-user-tie')
Menu.create(navigation_name: "Parametros del sistema", controller_name: "system_parameters", icon: 'fa-cog')
Menu.create(navigation_name: "Auditoria", controller_name: "audits", icon: 'fa-tasks')
Menu.create(navigation_name: "Metodos de Ensayo", controller_name: "sample_methods", icon: 'fa-flask')
Menu.create(navigation_name: "Categoria de muestra", controller_name: "sample_categories", icon: 'fa-tags')
Menu.create(navigation_name: 'Inventario', controller_name: 'inventories', icon: 'fa-clipboard-list')
Menu.create(navigation_name: "Servicios", controller_name: "client_services", icon: 'fa-scroll')
Menu.create(navigation_name: "Servicios", controller_name: "employee_services", icon: 'fa-scroll')
Menu.create(navigation_name: "Proformas", controller_name: "employee_quotations", icon: 'fa-scroll')
Menu.create(navigation_name: "Proformas", controller_name: "client_quotations", icon: 'fa-scroll')
Menu.create(navigation_name: "Custodias asignadas", controller_name: "employee_custody_orders", icon: 'fa-hammer')
Menu.create(navigation_name: "Ordenes de custodia", controller_name: "supervisor_custody_orders", icon: 'fa-hammer')
